name: react-with-davegray
config:
  webroot: .
services:
  node:
    type: node:16
    build:
      - npm install npx -g
      - npm install create-react-app -g
    overrides:
      ports: [3000:3000]
tooling:
  node:
    service: node
  npm:
    service: node
  npx:
    service: node