name: react-with-davegray
config:
  webroot: .
services:
  node:
    api: 3
    type: node:16
    build:
      - npm install npx -g
      - npm install create-react-app -g
    port: 3000
tooling:
  node:
    service: node
  npm:
    service: node
  npx:
    service: node
proxy:
  node:
    - react-with-davegray.lndo.site:3000